# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import users_list.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_list', '0002_userprofile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='random_number',
            field=models.IntegerField(default=users_list.models.get_random_number),
        ),
    ]
